#define     ACQ_STARTED_OK						1
#define     ACQ_STARTED_NO						-1

#define     ACQ_STOPPED_OK	               1
#define     ACQ_STOPPED_NO	               -1

#define     ACQ_PAUSED_OK		            1
#define     ACQ_PAUSED_NO		            -1	

#define     ACQ_RESUMED_OK		            1
#define     ACQ_RESUMED_NO		            -1	

#define     IMP_STARTED_OK	               1
#define     IMP_STARTED_NO	               -1

#define     IMP_STOPPED_OK	               1
#define     IMP_STOPPED_NO	               -1

#define     TM_STARTED_OK	               1
#define     TM_STARTED_NO	               -1

#define     TM_STOPPED_OK	               1
#define     TM_STOPPED_NO	               -1

#define     INIT_SESSION_OK						1
#define     INIT_SESSION_NO						-1
#define     INIT_SESSION_NO_DEFFILE_FAILED		-2
#define     INIT_SESSION_NO_DESTFILE_FAILED		-3

#define     SET_MARKER_OK	               1
#define     SET_MARKER_NO	               -1

#define     ID_WRONG_SEQUENCY_OF_COMMAND  0

#define		NOT_IMPLEMENTED					0


//errors
#define ABM_ERROR_SDK_ACQUISITION_STOPPED			 100
#define ABM_ERROR_SDK_NO_DATA_ARRIVING				 101
#define ABM_ERROR_SDK_CREATE_MAIN_WINDOW_FAILED		 110
#define ABM_ERROR_SDK_COULDNT_FIND_DEVICE            120
#define ABM_ERROR_SDK_COULDNT_CONNECT_DEVICE		 121
#define ABM_ERROR_SDK_COULDNT_START_REALTIME         150
#define ABM_ERROR_SDK_COULDNT_START_SAVING			 151
#define ABM_ERROR_SDK_COULDNT_STOP_REAL_TIME		 170
#define ABM_ERROR_SDK_COULDNT_LOAD_CHANNEL_MAP	     180
#define ABM_ERROR_SDK_WRONG_SESSION_TYPE			 190
#define ABM_ERROR_SDK_WRONG_INPUT_SETTINGS			 191
#define ABM_ERROR_SDK_WRONG_FILE_PATHS				 192
#define ABM_ERROR_SDK_CLASSIFICATION_INIT_FAILED     193
#define ABM_ERROR_SDK_COULDNT_CLOSE_CONNECTION	     194
#define ABM_ERROR_SDK_NOTSET_DEFFILE				 195
#define ABM_ERROR_SDK_WRONG_DESTPATH				 196
#define ABM_ERROR_SDK_TOO_LARGE_MISSED_BLOCK		 197




#define ABM_ERROR_SDK_COMMAND_IMP_START_FAILED				160
#define ABM_ERROR_SDK_COMMAND_IMP_STOP_FAILED				161
#define ABM_ERROR_SDK_COMMAND_IMP_HIGH_FAILED				162
#define ABM_ERROR_SDK_COMMAND_IMP_LOW_FAILED				163
#define ABM_ERROR_SDK_COMMAND_IMP_START_FAILED_IGNORED      164

#define ABM_ERROR_SDK_INVALID_ESU_CONFIG_MULTIPLE_PORTS	    140
#define ABM_ERROR_SDK_INVALID_ESU_CONFIG_NO_PORTS		    141
#define ABM_ERROR_SDK_INVALID_ESU_CONFIG_COM1				142
#define ABM_ERROR_SDK_INVALID_ESU_CONFIG_COM2				143
#define ABM_ERROR_SDK_INVALID_ESU_CONFIG_COM3				144
#define ABM_ERROR_SDK_INVALID_ESU_CONFIG_COM4				145
#define ABM_ERROR_SDK_INVALID_ESU_CONFIG_LPT				146


//warnings
#define ABM_WARN_SDK_ACQUISITION_STOPPED   200
#define ABM_WARN_SDK_COULDNT_CONNECT	   230
#define ABM_WARN_SDK_DEVICE_NOT_FOUND      250
#define ABM_WARN_SDK_TIMESTAMP_WO_SAMPLE   260


